# Generated by Django 4.2.6 on 2023-12-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutimages_cropping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutImages',
            new_name='AboutImage',
        ),
    ]
