# Generated by Django 4.2.6 on 2023-11-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
