# Generated by Django 4.2.6 on 2023-11-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_framework_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_url', models.CharField(max_length=300)),
            ],
        ),
    ]
