# Generated by Django 4.2.6 on 2023-11-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='WebProfile',
        ),
    ]
