# Generated by Django 4.2.6 on 2023-11-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_profiles_webprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programminglanguage',
            old_name='programming_language',
            new_name='programming_language_name',
        ),
    ]
