# Generated by Django 4.2.6 on 2023-12-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_myapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('continent', models.CharField(default='Unknown', max_length=20)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=150)),
            ],
        ),
    ]
