# Generated by Django 4.2.6 on 2023-11-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
